// Shared configuration: the package's flavours, where emsdk and generated files live, and the project layout.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

export const HOME = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
export const FLAVORS_FILE = path.join(HOME, 'flavors.json');
export const spec = JSON.parse(fs.readFileSync(FLAVORS_FILE, 'utf8'));
export const FLAVORS = Object.keys(spec.flavors);

// Everything machine-wide (emsdk installs, generated wrapper config) lives in one cache so projects share it.
export const CACHE = process.env.WBA_CACHE || path.join(os.homedir(), '.cache', 'wasm-build-all');
export const EMSDK = process.env.WBA_EMSDK || path.join(CACHE, `emsdk-${spec.emsdk}`);
export const GEN = path.join(CACHE, 'gen');

export function flavor(name) {
  const f = spec.flavors[name];
  if (!f) throw new Error(`unknown flavour "${name}" (have: ${FLAVORS.join(', ')})`);
  const c = spec.common;
  return {
    name,
    threads: f.threads,
    compile: [...c.compile, ...f.compile],
    link: [...c.link, ...f.link],
    nodeTest: [...c.nodeTest, ...f.nodeTest],
    webTest: [...c.webTest, ...f.webTest],
  };
}

export function nodeBinary() {
  const dir = path.join(EMSDK, 'node');
  const v = fs.existsSync(dir) ? fs.readdirSync(dir).sort().pop() : null;
  if (!v) throw new Error(`no node in ${dir}: run wasm-build-all setup`);
  return path.join(dir, v, 'bin', 'node');
}

// The project is the nearest directory (from cwd up) with a wasm-build-all.json.
export function project(start = process.cwd()) {
  for (let d = path.resolve(start); ; d = path.dirname(d)) {
    const f = path.join(d, 'wasm-build-all.json');
    if (fs.existsSync(f)) {
      const cfg = JSON.parse(fs.readFileSync(f, 'utf8'));
      return {
        root: d,
        recipes: path.join(d, cfg.recipes || 'recipes'),
        sysrootBase: path.join(d, cfg.sysroot || 'sysroot'),
        dist: path.join(d, cfg.dist || 'dist'),
        order: cfg.order || [],
        pins: cfg.pins || null,
        packages: cfg.packages || null,   // GitHub owner of the <recipe>-wasm64 repos
      };
    }
    if (d === path.dirname(d)) return null;
  }
}

export const sysroot = (proj, fl) => path.join(proj.sysrootBase, `wasm64-${fl}`);

const q = (a) => `'${String(a).replace(/'/g, `'\\''`)}'`;
export const shellWords = (arr) => arr.map(q).join(' ');

// Bash fragment the compiler wrapper sources on every call (no node startup per compile).
export function writeGenerated() {
  fs.mkdirSync(GEN, { recursive: true });
  let sh = `# Generated by wasm-build-all setup from ${FLAVORS_FILE}; do not edit.\nWBA_EMSDK_DIR=${q(EMSDK)}\n`;
  for (const n of FLAVORS) {
    const f = flavor(n);
    sh += `WBA_COMPILE_${n}=(${shellWords(f.compile)})\nWBA_LINK_${n}=(${shellWords(f.link)})\n`;
  }
  fs.writeFileSync(path.join(GEN, 'flavors.sh'), sh);
  fs.writeFileSync(path.join(GEN, 'paths.cmake'),
    `# Generated by wasm-build-all setup; do not edit.\nset(WBA_HOME "${HOME}")\nset(WBA_EMSDK "${EMSDK}")\nset(WBA_FLAVORS_FILE "${FLAVORS_FILE}")\n`);
}
