// `wasm-build-all env <flavour>`: shell exports for building with a flavour, for `eval "$(wasm-build-all env mt)"`.
// Also writes the flavour's meson cross file into the sysroot.
import fs from 'node:fs';
import path from 'node:path';
import { HOME, EMSDK, GEN, flavor, nodeBinary, project, sysroot } from './config.mjs';

export function envFor(name, proj = project()) {
  const f = flavor(name);
  if (!fs.existsSync(path.join(GEN, 'flavors.sh'))) throw new Error('run wasm-build-all setup first');
  const root = proj ? proj.root : process.cwd();
  const sr = proj ? sysroot(proj, name) : path.join(root, 'sysroot', `wasm64-${name}`);
  for (const d of ['lib/pkgconfig', 'include', 'bin', 'share/wba']) fs.mkdirSync(path.join(sr, d), { recursive: true });
  const bin = path.join(HOME, 'bin');
  const cc = path.join(bin, `wasm64-${name}-emcc`), cxx = path.join(bin, `wasm64-${name}-em++`);
  const opt = process.env.WBA_OPT || '-O3';
  const link = [...f.compile, ...f.link];
  const env = {
    WBA_HOME: HOME, WBA_FLAVOR: name, WBA_THREADS: f.threads ? '1' : '0', WBA_ROOT: root, WBA_SYSROOT: sr,
    WBA_EMSDK: EMSDK, EMSDK, EM_NODE_JS: nodeBinary(), WBA_NODE: nodeBinary(),
    PATH: `${bin}:${path.join(EMSDK, 'upstream', 'emscripten')}:${process.env.PATH}`,
    CC: cc, CXX: cxx, WBA_OPT: opt,
    // The wrappers add the ABI flags to every compile/link; these carry optimisation and search paths only.
    CFLAGS: `${opt} -I${sr}/include`, CXXFLAGS: `${opt} -I${sr}/include`, LDFLAGS: `-L${sr}/lib`,
    PKG_CONFIG_LIBDIR: `${sr}/lib/pkgconfig:${sr}/share/pkgconfig`,
    WBA_CMAKE_TOOLCHAIN: path.join(HOME, 'cmake', 'wasm-build-all.cmake'),
    WBA_ABI: f.compile.join(' '),
    WBA_LDFLAGS: link.join(' '),
    WBA_NODE_TEST_LDFLAGS: f.nodeTest.join(' '),
    WBA_WEB_TEST_LDFLAGS: f.webTest.join(' '),
    WBA_SSE_FLAGS: '-msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2',
    WBA_MESON_CROSS: path.join(sr, 'meson-cross.ini'),
  };
  fs.writeFileSync(env.WBA_MESON_CROSS, mesonCross(env, sr));
  return env;
}

function mesonCross(env, sr) {
  const list = (s) => `[${s.split(/\s+/).filter(Boolean).map((a) => `'${a}'`).join(', ')}]`;
  const em = path.join(EMSDK, 'upstream', 'emscripten');
  return `# Generated by wasm-build-all env; do not edit.
[binaries]
c = '${env.CC}'
cpp = '${env.CXX}'
ar = '${em}/emar'
ranlib = '${em}/emranlib'
pkg-config = 'pkg-config'
exe_wrapper = '${path.join(HOME, 'bin', 'wasm-run')}'

[built-in options]
c_args = ${list(env.CFLAGS)}
cpp_args = ${list(env.CXXFLAGS)}
c_link_args = ${list(`${env.LDFLAGS} ${env.WBA_NODE_TEST_LDFLAGS}`)}
cpp_link_args = ${list(`${env.LDFLAGS} ${env.WBA_NODE_TEST_LDFLAGS}`)}
default_library = 'static'
# Link transitive Requires.private of static .pc files (e.g. libbrotlidec -> libbrotlicommon).
prefer_static = true
prefix = '${sr}'

[properties]
needs_exe_wrapper = true
pkg_config_libdir = '${env.PKG_CONFIG_LIBDIR}'

[host_machine]
system = 'emscripten'
cpu_family = 'wasm64'
cpu = 'wasm64'
endian = 'little'
`;
}

export const exportsFor = (env) =>
  Object.entries(env).map(([k, v]) => `export ${k}='${String(v).replace(/'/g, `'\\''`)}'`).join('\n');
