# CMake toolchain for wasm-build-all: Emscripten, wasm64, one flavour's flags (from flavors.json), one sysroot.
#   cmake -DCMAKE_TOOLCHAIN_FILE=$WBA_CMAKE_TOOLCHAIN ...   (after eval "$(wasm-build-all env <flavour>)")
# Flavour and sysroot come from WBA_FLAVOR / WBA_SYSROOT (environment or -D); flavour defaults to mt.
cmake_minimum_required(VERSION 3.20)
if(DEFINED ENV{WBA_CACHE})
  set(_wba_cache "$ENV{WBA_CACHE}")
else()
  set(_wba_cache "$ENV{HOME}/.cache/wasm-build-all")
endif()
include("${_wba_cache}/gen/paths.cmake" OPTIONAL RESULT_VARIABLE _wba_paths)
if(NOT _wba_paths)
  message(FATAL_ERROR "wasm-build-all: ${_wba_cache}/gen/paths.cmake missing; run wasm-build-all setup")
endif()
if(DEFINED ENV{WBA_EMSDK})
  set(WBA_EMSDK "$ENV{WBA_EMSDK}")
endif()
foreach(_v WBA_FLAVOR WBA_SYSROOT)
  if(NOT ${_v} AND DEFINED ENV{${_v}})
    set(${_v} "$ENV{${_v}}")
  endif()
endforeach()
if(NOT WBA_FLAVOR)
  set(WBA_FLAVOR mt)
endif()
if(NOT WBA_SYSROOT)
  set(WBA_SYSROOT "${CMAKE_SOURCE_DIR}/sysroot/wasm64-${WBA_FLAVOR}")
endif()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES WBA_FLAVOR WBA_SYSROOT)

# Flags from flavors.json: common + the flavour's own, per kind (compile, link, nodeTest).
file(READ "${WBA_FLAVORS_FILE}" _wba_json)
function(_wba_flags kind out)
  set(_r "")
  foreach(_sec "common" "flavors;${WBA_FLAVOR}")
    string(JSON _n ERROR_VARIABLE _err LENGTH "${_wba_json}" ${_sec} ${kind})
    if(_err)
      message(FATAL_ERROR "wasm-build-all: no flavour '${WBA_FLAVOR}' in ${WBA_FLAVORS_FILE}")
    endif()
    if(_n GREATER 0)
      math(EXPR _last "${_n} - 1")
      foreach(_i RANGE ${_last})
        string(JSON _f GET "${_wba_json}" ${_sec} ${kind} ${_i})
        string(APPEND _r " ${_f}")
      endforeach()
    endif()
  endforeach()
  set(${out} "${_r}" PARENT_SCOPE)
endfunction()
_wba_flags(compile _wba_compile)
_wba_flags(link _wba_link)
_wba_flags(nodeTest _wba_node)

include("${WBA_EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake")
# Emscripten's platform file decides the pointer size from CMAKE_C_FLAGS containing -m64, but our ABI flags come
# from the launcher, so it concludes wasm32. It runs again inside every project(), so the 64-bit values are
# re-applied after each project() (CMAKE_PROJECT_INCLUDE) and once here.
set(CMAKE_PROJECT_INCLUDE "${WBA_HOME}/cmake/project-include.cmake")
include("${WBA_HOME}/cmake/project-include.cmake")

# Every compile and link goes through wba-launch, which always adds the ABI flags (a project that sets
# CMAKE_C_FLAGS/CMAKE_CXX_FLAGS would otherwise drop the *_FLAGS_INIT values below).
foreach(_l C CXX)
  set(CMAKE_${_l}_COMPILER_LAUNCHER "${WBA_HOME}/bin/wba-launch;${WBA_FLAVOR}" CACHE STRING "")
  set(CMAKE_${_l}_LINKER_LAUNCHER "${WBA_HOME}/bin/wba-launch;${WBA_FLAVOR}" CACHE STRING "")
endforeach()
set(CMAKE_C_FLAGS_INIT "${_wba_compile}")
set(CMAKE_CXX_FLAGS_INIT "${_wba_compile}")
set(CMAKE_C_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_wba_compile}${_wba_link}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_wba_compile}${_wba_link}")
# Executables built by upstream projects are their test programs: runnable by ctest under node with the host
# filesystem. Set WBA_NODE_TESTS=OFF for programs meant for the browser.
if(NOT DEFINED WBA_NODE_TESTS)
  set(WBA_NODE_TESTS ON)
endif()
if(WBA_NODE_TESTS)
  set(CMAKE_EXE_LINKER_FLAGS_INIT "${_wba_compile}${_wba_link}${_wba_node}")
else()
  set(CMAKE_EXE_LINKER_FLAGS_INIT "${_wba_compile}${_wba_link}")
endif()
set(CMAKE_CROSSCOMPILING_EMULATOR "${WBA_HOME}/bin/wasm-run" CACHE FILEPATH "" FORCE)

# Static libraries, installed into and found in the sysroot.
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(CMAKE_INSTALL_PREFIX "${WBA_SYSROOT}" CACHE PATH "")
list(APPEND CMAKE_FIND_ROOT_PATH "${WBA_SYSROOT}")
list(APPEND CMAKE_PREFIX_PATH "${WBA_SYSROOT}")
